# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feaconf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feaconf.proto',
  package='xdl.io',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rfeaconf.proto\x12\x06xdl.io\"\x8c\x01\n\rFeatureOption\x12\x0c\n\x04name\x18\x01 \x02(\t\x12!\n\x04type\x18\x02 \x02(\x0e\x32\x13.xdl.io.FeatureType\x12\x12\n\nserialized\x18\x03 \x01(\x08\x12\x0c\n\x04nvec\x18\x04 \x01(\x05\x12\r\n\x05table\x18\x05 \x01(\x05\x12\x0b\n\x03\x64sl\x18\x06 \x01(\t\x12\x0c\n\x04mask\x18\x07 \x03(\r*\x1b\n\tConstants\x12\x0e\n\nkTablesMax\x10\x04*&\n\x0b\x46\x65\x61tureType\x12\x0b\n\x07kSparse\x10\x01\x12\n\n\x06kDense\x10\x02')
)

_CONSTANTS = _descriptor.EnumDescriptor(
  name='Constants',
  full_name='xdl.io.Constants',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kTablesMax', index=0, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=168,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_CONSTANTS)

Constants = enum_type_wrapper.EnumTypeWrapper(_CONSTANTS)
_FEATURETYPE = _descriptor.EnumDescriptor(
  name='FeatureType',
  full_name='xdl.io.FeatureType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kSparse', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDense', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=197,
  serialized_end=235,
)
_sym_db.RegisterEnumDescriptor(_FEATURETYPE)

FeatureType = enum_type_wrapper.EnumTypeWrapper(_FEATURETYPE)
kTablesMax = 4
kSparse = 1
kDense = 2



_FEATUREOPTION = _descriptor.Descriptor(
  name='FeatureOption',
  full_name='xdl.io.FeatureOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='xdl.io.FeatureOption.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='xdl.io.FeatureOption.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized', full_name='xdl.io.FeatureOption.serialized', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nvec', full_name='xdl.io.FeatureOption.nvec', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='xdl.io.FeatureOption.table', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dsl', full_name='xdl.io.FeatureOption.dsl', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='xdl.io.FeatureOption.mask', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=166,
)

_FEATUREOPTION.fields_by_name['type'].enum_type = _FEATURETYPE
DESCRIPTOR.message_types_by_name['FeatureOption'] = _FEATUREOPTION
DESCRIPTOR.enum_types_by_name['Constants'] = _CONSTANTS
DESCRIPTOR.enum_types_by_name['FeatureType'] = _FEATURETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureOption = _reflection.GeneratedProtocolMessageType('FeatureOption', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREOPTION,
  __module__ = 'feaconf_pb2'
  # @@protoc_insertion_point(class_scope:xdl.io.FeatureOption)
  ))
_sym_db.RegisterMessage(FeatureOption)


# @@protoc_insertion_point(module_scope)
